[package]
name = "srhd"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = { version = "0.5.3", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
service-manager = "0.7"
clap = { version = "4.5.18", features = ["derive"] }
